[template]
cargo_generate_version = ">=0.23.0"
ignore = [
  "cargo-generate.toml",
  ".env",
  "*.local",
  "target",
  "secrets",
]
include = [
  "Cargo.toml",
  "Cargo.toml.liquid",
  "README.md",
  "README.md.liquid",
]
